zorchenhimer/MoviePolls

- .gitignore
- Makefile
- config.json
- dataimporter.go
- server.go
- static/site.css
- templates/add-movie.html
At the moment links to imdb and myanimelist are supported, more support can be added via the dataapi interface in dataimporter.go
I had to do some restructuring in server.go to implement the changes.
I also added a new file "config.json" to store the API Key for TMdb (API for imdb).
For the Myanimelist integration the Jikan API is used.
Posters get saved locally (as requested)
Some error handling is already implemented but it still needs some work.
I also worked on the CSS file to improve the looks of the site.
> Added autofill functionality to the Add Movie Prompt

- admin.go
- config.json
- dataimporter.go
- server.go
- templates.go
- templates/add-movie.html
- templates/admin/config.html
Removed panics, added the new Field "ErrAutofill" in data, added handling for this new field in the template files
> Improved Error handling

- server.go
moved logic into a separate function
commented error sources
cleaned up autofill code
(dont mind the first 2 commits, i just checked my email settings)
> Refactoring of autofill

- server.go
- templates/cycle.html
This PR adds a notice for the last ended Cycle and the watched movies from this cycle.
This fixes #12.
This needed a new field "LastCycle" to be added to the data struct for the cycles.html serving.
The LastCycle field utilizes the GetPastCycles function to retrive the last ended cycle.
I also added a css class "cycleHistory" for future css styling (but none of my bussiness :P)
> Adding history display

- server.go
This should fix one part of #47, the movie title validation is still
todo.
> Moved the autofillbox check before the other field checks

- server.go
- templates/cycle.html
This PR fixes #11, closes #43  and add some improvements for the movie history display on the main page.
> Issue #11 - Info on upcoming MovieNight and some other fixes 

- server.go
> Added a size check to the get anime id regex result

- admin.go
- common/util.go
- server.go
- templates.go
- templates/add-movie.html
This PRs goal is to improve overall readability of the code as well as reducing the size of the biggest function in server.go.
When this will get merged into master it will fix #60.
> Rewrite#60

- common/util.go
- server.go
This PR contains two fixes for link related issues.
One commit fixes #61 by adapting the regex.
The other commit fixes #62 by introducing a new function to strip the ref link from the input links.
This PR is based on the PR from #63 therefore it should be merged AFTER #63 is merged.
> Link improvements

- common/movie.go
- common/tag.go
- common/util.go
- data/connector.go
- data/json.go
- dataimporter.go
- server.go
- templates/movie-info.html
This PR closes #24 with 221e065 and the following commits.
This PR also closes #68 with 70b4089 to e5789e6.
While adding further metadata (duration/rating) was fairly easy (although i needed to do an additional API request for imdb movies) supporting tags was on a whole different level.
To support Tags a new Tag slice was created of the structure
```
type Tag struct {
Id   int
Name string
}
```
This new struct was added to the database connector with some simple Add/Get/Find/Delete functions.
To support searching Movies by tag a new function "FilterMoviesByTags" was created which takes a slice of movies and a slice of tags to be found and returns all movies of the original slice that contain the tags to look for.
I also added a new div in the viewMovie.html to render the new metadata and …
> Movie rework #24,68

- dataimporter.go
Just a quick PR to get it out of my dev environment :)
> Added imdb or mal tag to the autofilled movies

- common/util.go
- go.mod
- go.sum
- server.go
As discussed i added the library  to all input validation length checks.
If you want to test it the nightly build is updated to run the feature branch.
> Text length#46

- contributing.md
- readme.md
Not much more to say - closes #40
> Added contribution guidelines and development aids to readme

- data/connector.go
- data/json.go
- templates/account.html
- user.go
This PR enables a user to see which movies have been added by him/herself in the account page.
Closes #81
> Adding functionality to display the movies a user has added

- data/json.go
- go.mod
Added functionality to create 'db/' directory if it does not already exist to mitigate the need to manually create it on first start.
> Fix for issue #94: Create 'db/' directory if not exists.

- templates/cycle.html
> Added epic's solution for dynamic search

- web/templates/account.html
We never actually used the SuccessMessage field in the data struct, this
new element uses it to display the success message to the user after
successfully changing their password, fixes #120
> Display Success Message when a user changes his/her password

- web/static/css/site.css
- web/templates/add-movie.html
- web/templates/movie-info.html
This is the partial code for 'Project-Css-Rework', this PR is intended for preliminary review by repomaster.
> Partial CSS-Rework code

- logic/config.go
- logic/dataimporter.go
- logic/movies.go
Several fixes regarding image upload handling initiated by #115
fixes #115
> 115 image upload fixes

- logic/movies.go
- web/pageAddMovie.go
> 126 movie create redirect fix

- .golangci.yml
- logger/logger.go
- logic/dataimporter.go
- logic/logic.go
- logic/movies.go
- logic/security.go
- logic/user.go
- models/util.go
- web/handlerVote.go
- web/handlersAuth.go
- web/pageAddMovie.go
- web/pageAdmin.go
- web/pageHistory.go
- web/pageMain.go
- web/pageMovie.go
- web/pageUser.go
- web/session.go
- web/template_structs.go
For linting [golangci-lint](https://golangci-lint.run/) was used, a corresponding configuration is provided.
A few linter settings are to be discussed but i think this is a good basis.
> Added linter setup and fixed all current errors

- web/static/css/site.css
- web/templates/cycle.html
- web/templates/movie-info.html
> Added back the vote button on the movie page.
